### ISSUE TITLE
tition.io - Development - Left Menu Jumping

### ISSUE THREAD

**Issue by TraderStf** [titon/toolkit#114] opened 2015-03-25 15:39 UTC
Hi,

In the [Development tab](http://titon.io/en/toolkit/2.1.0/development/js/class#prototype-override), when the right part has to scroll up or down, the left menu is blinking and jumping up and down, let's say 10px up-down while the scroll is occuring.

To see it, use the link just above.
Click on "Super Methods" then on "Creating A Class".

This jumpy menu is only in Mac OS X Yosemite - Safari, all latest, no extra.
It is ok in Chrome, Firefox nor Opera.

**Comment by milesj** [comment] 2015-03-25 20:58
What's your screen resolution? Can't reproduce on my laptop.

**Comment by TraderStf** [comment] 2015-03-26 09:16
Intel HD Graphics 4000 - 1024 MB
Acer 23" - 1920 x 1080 - Colors 32 bits (ARGB8888)
Restart or reboot safari or the mac mini does not change.

When I load (that) page, I get this in Safari Inspector:
<pre>[Warning] Unexpected CSS token: : (style.min.css, line 4, x5)</pre>

I have disabled all things that might have some influence SaneDesk, Safari Extensions disabled.

Modules in Safari:
Google Talk Plugin - Version 5.40.2.0 - file " googletalkbrowserplugin.plugin "
Google Talk Plugin Video Renderer - Version 5.40.2.0 - file " o1dbrowserplugin.plugin "
QuickTime Plug-in 7.7.3
Shockwave Flash 17.0 r0 - file " Flash Player.plugin "

**Comment by TraderStf** [comment] 2015-03-26 12:56
I just notice that the left menu block totally disappears when the window width becomes less than ~978.

When it becomes less than ~630 it reappears on top of the page (below big icons tabs, it is ok) and its (1) width is the ~same as the window, i.e. ~630.

In this situation, if you scroll up, the menu shrink to its usual width and stays over the page content below which is scrolled up, see also some Alert (yellow note) are above the menu block.

After that scroll up, if you scroll down to see the top of the page, a bit after you see the top of the (first) H1 (e.g. "Class System"), the left menu changes to occupy ~all the width of the window (1).

![menuwidth](https://cloud.githubusercontent.com/assets/5954335/6846531/5be6b85e-d3bf-11e4-81fc-fb05f39bf5d0.png)


I suppose that the jumping of the left menu block is the reason that the small grey scroll bar inside it, has 'gap/hole' from times to times during the scrolling of the main content:

![scrollbargap](https://cloud.githubusercontent.com/assets/5954335/6846538/5f34c74e-d3bf-11e4-83e2-9821d8ce4898.png)

**Comment by TraderStf** [comment] 2015-03-26 13:03
BTW, I love this framework, 'Flexible Style' i.e. outside the code!

It is far better than those similar to BootS---trap 😜

**Comment by TraderStf** [comment] 2015-03-31 09:49
I made 2 movies but probably the recording is not fast enough, the jumps are more frequent and faster that in the movie and their are occuring almost all the time of the movie/scroll.

The only moments you almost see what I have on screen is when I click on the menus.
Once again more frequent and faster, one jump is made of 2-3 flashes/blinks, in the movie you see only one flash per jump.

[jump2](https://www.moureau.me/4titon/2015-03-31-jumpinmenu2.swf)

[jump1](https://www.moureau.me/4titon/2015-03-31-jumpinmenu2.swf)

**Comment by milesj** [comment] 2015-04-06 17:04
The issue with the sidebar appearing over the documentation should be fixed.

Will look into the jumping later today. I believe it might be caused by the event throttling.

**Comment by milesj** [comment] 2015-05-06 05:38
I can't seem to find the issue with the jumping. I cannot reproduce it on Windows Firefox but I can on Windows Chrome/IE11. I also can't reproduce on Mac Firefox/Chrome. 

Doesn't make much sense as the `top` property is modified at each scroll event, so it shouldn't stutter. I just wonder if the logic is taking longer than the repaint.

**Comment by milesj** [comment] 2016-02-12 00:17
The demo site is currently being redesigned. Closing this ticket.

**Closed by milesj** 2016-02-12 00:17 UTC
Labels: bug, pin, website
